"""new fields

Revision ID: 998fadbf19b3
Revises: 83c946f36dc2
Create Date: 2019-10-09 20:59:14.637112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998fadbf19b3'
down_revision = '83c946f36dc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
